import 'package:flutter/material.dart';
import 'package:thgportfolio/theme.dart';

class AISummarySection extends StatelessWidget {
  const AISummarySection({super.key});

  @override
  Widget build(BuildContext context) {
    final textTheme = Theme.of(context).textTheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('AI Summary', style: textTheme.headlineMedium),
        const SizedBox(height: 24),
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(20),
          decoration: BoxDecoration(
            color: gruberBg,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: gruberYellow.withValues(alpha: 0.2), width: 1.5),
            boxShadow: [
              BoxShadow(
                color: gruberYellow.withValues(alpha: 0.05),
                blurRadius: 10,
                spreadRadius: 2,
              ),
            ],
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(Icons.psychology, color: gruberYellow, size: 24),
                  SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'Architectural & Tenacious Learner',
                      style: TextStyle(
                        color: gruberFg,
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              _buildSummaryPoint(
                'First-Principles Focus',
                'Tristan doesn\'t just "use" a tool; he seeks to understand its underlying mechanics. This is evident in his choice of modal editors like Helix/Vim and his interest in building custom CLIs and architectural patterns like FSA (Flutter Simple Architecture).',
              ),
              _buildSummaryPoint(
                'Proactive Problem Solver',
                'He approaches technical roadblocks—such as dependency conflicts or infrastructure friction—not as nuisances, but as opportunities to master the system. He prefers building custom automations over repetitive manual tasks.',
              ),
              _buildSummaryPoint(
                'Efficiency-Driven Workflow',
                'His learning is deeply tied to developer productivity. By mastering terminal-based environments and building his own state-preservation hooks, he actively molds his environment to match his cognitive flow.',
              ),
              _buildSummaryPoint(
                'Full-Stack Versatility',
                'Transitioning from Civil Engineering to Software Development, he demonstrates a high capacity for self-directed, rigorous study, moving fluidly between Flutter mobile apps, Dart backend servers, and terminal-based TUI tooling.',
              ),
              const SizedBox(height: 8),
              const Text(
                'Summary generated by Gemini based on our collaborative sessions.',
                style: TextStyle(
                  color: gruberQuartz,
                  fontSize: 12,
                  fontStyle: FontStyle.italic,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildSummaryPoint(String title, String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              color: gruberYellow,
              fontSize: 15,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            content,
            style: const TextStyle(
              color: gruberFg,
              fontSize: 14,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
}
