import "package:flutter/material.dart";

const Map<String, IconData> skillIcons = {
  "Dart": Icons.code,
  "Web (JavaScript, HTML, CSS)": Icons.web,
  "VBA": Icons.table_chart_outlined,
  "SQL": Icons.storage_outlined,
  "Kotlin": Icons.android,
  "Swift": Icons.phone_iphone,
  "Flutter": Icons.flutter_dash,
  "Jaspr (Dart Web Framework)": Icons.language,
  "MIT App Inventor": Icons.extension_outlined,
  "Serverpod": Icons.dns_outlined,
  "VS Code": Icons.code,
  "Android Studio": Icons.android,
  "Xcode": Icons.apple,
  "Helix/Vim/Neovim": Icons.terminal,
  "Codemagic": Icons.cloud_upload_outlined,
  "Git": Icons.source_outlined,
  "GitHub": Icons.code,
  "Bitbucket": Icons.account_tree_outlined,
  "Sourcetree": Icons.account_tree,
  "Google Apps Script": Icons.data_object,
  "Firebase": Icons.local_fire_department_outlined,
  "Trello": Icons.view_kanban_outlined,
  "Postman": Icons.api_outlined,
  "Google Cloud Platform": Icons.cloud_outlined,
  "OpenCode": Icons.terminal,
  "Gemini CLI": Icons.auto_awesome,
  "LM Studio": Icons.desktop_windows_outlined,
  "Google AI Studio": Icons.science_outlined,
  "Ollama": Icons.smart_toy_outlined,
  "Firebase Studio": Icons.developer_mode,
  "Figma": Icons.design_services_outlined,
  "OMP": Icons.terminal,
  "Codex": Icons.smart_toy_outlined,
  "Claude Code": Icons.smart_toy,
  "Antigravity 2": Icons.rocket_launch_outlined,
  "Bash": Icons.terminal,
  "PowerShell": Icons.terminal,
};
